Add description for plugin
prontotools/gravityforms-total-amount-shortcode pull request #2
Opened 2017-08-11 06:16 UTC by sandysaille

Add more release files, icon, and banner for this plugin to push to Wordpress.org

2017-08-11 06:47 UTC, zkan requested changes

2017-08-11 06:47 UTC, zkan commented on .travis.yml
> +    - hhvm
We don't need HHVM anymore, I think. Let's remove it.

2017-08-11 06:47 UTC, zkan commented on readme.txt
> +* First release!
We should write a short description here. Maybe a short summary of what this plugin can do?

2017-08-11 06:53 UTC, sandysaille commented
@zkan Please review again ka.

2017-08-11 09:12 UTC, sandysaille commented
@zkan Please review again ka _/\_

2017-08-11 11:28 UTC, zkan commented
@sandysaille I mean the change log section ja, not the description. Please revert the description back. >_<

2017-08-17 06:51 UTC, sandysaille commented
@zkan Oopss sorry ka, fixed it. Please review again ka.

2017-09-11 07:06 UTC, zkan approved these changes

2017-09-11 07:06 UTC, merged